export const PRODUCT_SHOWCASE_DATA = {
  "lick-salt-natural": {
    hero: {
      title: "Himalayan Salt Lick",
      subtitle: "(Natural)",
      image: "/North%20himaliyan%20salt/natural/idrees.png",
      description:
        "Natural Himalayan Lick Salt is a 100% pure, unrefined mineral salt block sourced from the world-famous Himalayan Salt Range in Pakistan. This premium pink rock salt is rich in essential trace minerals and provides a natural, chemical-free mineral supplement for livestock and farm animals.",
    },
    attributes: [
      ["Material", "Organic Material", "Product Type", "Animal Licking Rock Salt"],
      ["Technique", "Natural", "Shape", "Geometric Shape"],
      ["Style", "Rocks", "Application", "Durable, Other"],
      ["Feature", "Eco-Friendly", "Model Number", "MRALS-02"],
      ["Place of Origin", "Pakistan", "Brand Name", "MRPL"],
      ["Usage", "Animal Licking Salt", "Color", "Pink"],
      ["Weight", "2-3 KG", "Certification", "ISO9001 - ISO 22000"],
      ["Packing", "Bulk packing", "Delivery Time", "15 Days"],
      ["Shipping Methods", "By Sea", "MOQ", "100 Pieces"],
      ["Use", "Animal Salt Feed", "Regional Feature", "Worldwide"],
    ],
    descriptionParagraphs: [
      "Himalayan Salt Licks for Cattle, Horses, Goats & Livestock",
      "Premium Himalayan Salt Licks are a natural and essential mineral supplement designed to support the health, growth, and productivity of cattle, horses, goats, sheep, and other livestock. Sourced from pure Himalayan rock salt deposits, these mineral blocks provide vital nutrients that animals instinctively seek for optimal performance.",
      "Why Choose Himalayan Salt Licks?",
      "Himalayan salt licks are rich in natural sodium chloride (NaCl) along with trace minerals that help maintain healthy muscle function, improved feed intake, smooth and shiny coat, proper hydration balance, enhanced milk and meat production, and overall livestock performance.",
      "Salt deficiency in animals can lead to muscle cramps, rough coat, reduced appetite, chewing or licking unusual objects, and decreased productivity. Providing a high-quality mineral lick helps prevent these issues naturally.",
      "Essential Salt Intake for Horses",
      "All horses require salt in their daily diet for proper body function. According to the National Research Council (NRC), an average 1,100 lb horse at rest requires 25 grams of sodium chloride per day, horses in moderate work need approximately 55-65 grams per day, and horses with heavy workloads may require up to 200 grams per day.",
      "While some salt comes from grain rations and supplements, a Himalayan salt lick ensures your horse can self-regulate its intake. Most horses naturally consume only the amount their body needs.",
      "Perfect for All Livestock",
      "Our Himalayan mineral salt blocks are ideal for cattle, horses, goats, sheep, camels, and other farm animals. Harsh environmental conditions often expose natural mineral deposits that attract animals from miles away. Providing a salt lick replicates this natural behavior while ensuring consistent access to essential minerals.",
      "100% Natural & Weather Resistant",
      "Natural Himalayan rock salt, no artificial additives or chemicals, long-lasting and weather-resistant, and suitable for indoor and outdoor use.",
      "Give Your Livestock the Minerals They Need",
      "Support better growth, improved productivity, and overall animal health with our Himalayan Salt Licks for Livestock. A simple, natural, and effective way to ensure your animals receive essential minerals daily. Order now and enhance your farm's productivity naturally!",
    ],
    referenceImages: [
      "/North%20himaliyan%20salt/natural/nat11.png",
      "/North%20himaliyan%20salt/natural/nat22.jpeg",
      "/North%20himaliyan%20salt/natural/naturalMain.png",
    ],
  },
  "lick-salt-compressed": {
    hero: {
      title: "Himalayan Salt Lick",
      subtitle: "(Compressed)",
      image: "/North%20himaliyan%20salt/compressed/compressed.png",
      description:
        "Himalayan Lick Salt (Compressed) is a natural mineral salt block made from pure Himalayan pink salt. Rich in essential minerals, because of its compressed shape it is easy to consume. It provides a long-lasting and chemical-free mineral supplement for livestock such as horses, cattle, goats, and sheep.",
    },
    attributes: [
      ["Type", "Salt Lick", "Moisture (%)", "10"],
      ["Grade", "Top Grade", "Storage Type", "Dry cool place"],
      ["Specification", "Salt licking", "Shelf Life", "2 years"],
      ["Manufacturer", "Natural pure pink salt", "Ingredients", "Pink salt"],
      ["Content", "Animal licking salt", "Address", "Pakistan"],
      ["Instruction for use", "For licking", "Place of Origin", "Pakistan"],
      ["Use", "Cattle, Dog, Horse, Pig", "Admixture (%)", "1"],
      ["Packaging", "4 blocks in a box/bag", "Brand Name", "North Himalayan Traders"],
      ["Model Number", "NB Salt Blocks", "Appearance", "Block"],
      ["Usage", "Animal Nutrition Feed", "Color", "Brown"],
      ["Product type", "Animal Lick Products", "Advantage", "Promotes Feed Digestion"],
      ["Packing", "5 kg and 10 kg blocks", "", ""],
    ],
    descriptionParagraphs: [
      "Himalayan Salt Licks for Cattle, Horses, Goats & Livestock",
      "Premium Himalayan Salt Licks are a natural and essential mineral supplement designed to support the health, growth, and productivity of cattle, horses, goats, sheep, and other livestock. Sourced from pure Himalayan rock salt deposits, these mineral blocks provide vital nutrients that animals instinctively seek for optimal performance.",
      "Why Choose Himalayan Salt Licks?",
      "Healthy muscle function",
      "Improved feed intake",
      "Smooth and shiny coat",
      "Proper hydration balance",
      "Enhanced milk and meat production",
      "Overall livestock performance",
      "Salt deficiency in animals can lead to muscle cramps, rough coat, reduced appetite, chewing or licking unusual objects, and decreased productivity. Providing a high-quality mineral lick helps prevent these issues naturally.",
      "Essential Salt Intake for Horses",
      "All horses require salt in their daily diet for proper body function. According to the National Research Council (NRC), an average 1,100 lb horse at rest requires 25 grams of sodium chloride per day, horses in moderate work need approximately 55-65 grams per day, and horses with heavy workloads may require up to 200 grams per day.",
      "While some salt comes from grain rations and supplements, a Himalayan salt lick ensures your horse can self-regulate its intake. Most horses naturally consume only the amount their body needs.",
      "Perfect for All Livestock",
      "Cattle",
      "Horses",
      "Goats",
      "Sheep",
      "Camels",
      "Other farm animals",
      "Harsh environmental conditions often expose natural mineral deposits that attract animals from miles away. Providing a salt lick replicates this natural behavior while ensuring consistent access to essential minerals.",
      "100% Natural & Weather Resistant",
      "Natural Himalayan rock salt",
      "No artificial additives or chemicals",
      "Long-lasting and weather-resistant",
      "Suitable for indoor and outdoor use",
      "Give Your Livestock the Minerals They Need",
      "Support better growth, improved productivity, and overall animal health with our Himalayan Salt Licks for Livestock. A simple, natural, and effective way to ensure your animals receive essential minerals daily. Order now and enhance your farm's productivity naturally!",
    ],
    referenceImages: [
      "/North%20himaliyan%20salt/compressed/com11.png",
      "/North%20himaliyan%20salt/compressed/com22.png",
      "/North%20himaliyan%20salt/compressed/compressed.png",
    ],
  },
  "salt-tiles": {
    hero: {
      title: "Himalayan Salt",
      subtitle: "Tiles",
      image: "/North%20himaliyan%20salt/tiles/tiles.png",
      description:
        "Natural Himalayan Salt Tiles sourced from the Himalayan mountains. These premium salt tiles are widely used for spa walls, salt therapy rooms, wellness centers, and interior decoration. They create a warm, relaxing atmosphere while adding a unique and luxurious touch to modern spaces.",
    },
    attributes: [
      ["Material", "Material", "Product Type", "Salt tile"],
      ["Technique", "Technique", "Style", "Buddhism"],
      ["Place of Origin", "Place of Origin", "Brand Name", "Demaro Salt"],
      ["Model Number", "Model Number", "Product name", "Himalayan Salt Tiles"],
      ["Shape", "Shape", "Color", "Pink white orange"],
      ["MOQ", "MOQ", "Size", "Customized sizes"],
      ["Packing", "Packing", "Logo", "Customized logo"],
      ["Payment", "Payment", "Quality", "High quality"],
      ["Sample", "Sample", "", ""],
    ],
    descriptionParagraphs: [
      "Product Description",
      "Our natural pink salt blocks are carefully crafted to enhance both the functionality and visual appeal of salt rooms. Sourced from natural mineral deposits, these blocks provide a calming ambiance while supporting a healthier indoor environment.",
      "Improves Air Quality & Relaxation",
      "Natural pink salt helps create a soothing atmosphere in salt therapy rooms, promoting relaxation and contributing to a refreshing indoor environment.",
      "Ideal 2-3 cm Block Size",
      "Designed in practical 2-3 cm thickness, these blocks are perfect for constructing salt room walls and floors, ensuring easy handling and precise installation.",
      "Strong Industrial-Grade Salt Bricks",
      "Manufactured with durability in mind, these bricks are strong, reliable, and suitable for both residential and commercial wellness spaces.",
      "ISO Certified Quality",
      "Our salt blocks meet international ISO standards, guaranteeing safe, consistent, and high-quality materials for every project.",
      "Beautiful Natural Aesthetic",
      "The warm pink glow of Himalayan salt creates a relaxing and luxurious atmosphere, making salt rooms visually appealing while complementing modern wellness interiors.",
      "Quick and Easy Installation",
      "Lightweight yet sturdy, these blocks are easy to handle and install, helping reduce construction time, labor costs, and installation complexity.",
      "Smooth and Consistent Texture",
      "Each block features a uniform finish, ensuring a clean, polished look without rough or uneven surfaces.",
      "Built for Long-Term Durability",
      "Designed to withstand frequent use in wellness environments, the blocks maintain their structure and appearance for years, reducing maintenance and replacement needs.",
      "Flexible Design Possibilities",
      "Perfect for custom wall designs, flooring patterns, and decorative accents, allowing designers to create unique salt therapy spaces.",
      "Eco-Friendly Natural Material",
      "Made from naturally occurring mineral deposits with minimal processing, these blocks support sustainable and environmentally conscious wellness environments.",
      "Moisture Resistant",
      "Ideal for spa and wellness settings, the blocks resist humidity and moisture, maintaining strength and stability over time.",
      "Reliable Batch Consistency",
      "Strict quality control ensures uniform color, size, and composition, delivering consistent performance and a cohesive look in every installation.",
    ],
    referenceImages: [
      "/North%20himaliyan%20salt/tiles/Image_fx%20-%202026-03-19T153211.790.png",
      "/North%20himaliyan%20salt/tiles/Image_fx%20-%202026-03-19T153510.725.png",
      "/North%20himaliyan%20salt/tiles/Image_fx%20-%202026-03-19T153517.819.png",
    ],
  },
  "cooking-plates": {
    hero: {
      title: "Himalayan Salt",
      subtitle: "Cooking Plate",
      image: "/North%20himaliyan%20salt/cooking%20plate/cooking%20plate.png",
      description:
        "Himalayan cooking plates are natural gourmet salt slabs made from pure Himalayan pink salt. Perfect for grilling, cooking, chilling, and serving food, these plates add a subtle mineral flavor to dishes while providing a unique presentation.",
    },
    attributes: [
      ["Material", "Organic Material", "Product Type", "Himalayan Salt Slab"],
      ["Technique", "Grooved", "Style", "Taste of life"],
      ["Application", "New", "Feature", "Real Touch"],
      ["Shape", "Geometric Shape", "Place of Origin", "Pakistan"],
      ["Brand Name", "North Himalayan Traders", "Model Number", "MRNSB-08"],
      ["Product Name", "Plate / Bricks / Slabs and Blocks", "Dimensions", "12 x 8 x 1.5 inches"],
      ["Packing", "Individual box", "Shipment", "Sea"],
      ["Logo", "", "Certification", "ISO 22000, HACCP, GMP, HALAL"],
      ["OEM", "Accepted", "Quality", "Excellent"],
      ["Delivery Time", "20-25 Days", "Payment", "T/T"],
      ["Style", "Plate (Dimension)", "Use", "Cooking"],
      ["Region", "Pakistan", "", ""],
    ],
    descriptionParagraphs: [
      "Key Features",
      "Complete Package: Our bundle includes a 100% natural Himalayan salt cooking block and an iron steel holder designed to prevent rust. It also comes with a recipe pamphlet suitable for chefs, home cooks, and grill lovers.",
      "Enhanced Flavor: Elevate your meals with a sizzling, salty taste using our Himalayan salt block and holder set. Cook steak, seafood, and other meats on the stovetop or BBQ grill, or chill for cold dishes.",
      "Durable Metal Tray: Crafted from high-quality steel, our salt block holder offers robust support and protection to extend the life of your salt blocks.",
      "Stunning Serving Plate: Enhance presentation with natural pink crystals. The salt block can be chilled and used as a captivating serving plate for hot or cold dishes.",
      "Gift of Flavorful Creativity: A unique and thoughtful grilling accessory for chefs, dads, grill masters, and BBQ enthusiasts.",
      "Effortless Cleaning: Thanks to the natural disinfectant properties of salt, simply wipe with a wet cloth and air dry.",
      "Unleash Natural Flavors: The natural Himalayan salt block infuses ingredients with authentic mineral flavor.",
      "Versatile Cooking Companion: From grilling and searing to chilling and presenting, this block adapts to many cooking techniques and serving styles.",
    ],
    referenceImages: [
      "/North%20himaliyan%20salt/cooking%20plate/Gemini_Generated_Image_17coe517coe517co.png",
    ],
  },
  "pink-salt": {
    hero: {
      title: "Himalayan Edible",
      subtitle: "Salt",
      image: "/North%20himaliyan%20salt/pink%20salt/salt.png",
      description:
        "Himalayan edible salt is a pure and natural mineral-rich salt sourced from the Himalayan region of Pakistan. Known for its natural pink color and essential trace minerals, it is widely used for cooking, seasoning, and healthy food preparation.",
    },
    attributes: [
      ["Type", "Himalayan Salt", "Form", "Solid"],
      ["Storage Type", "Dry Place", "Specification", "100% Natural"],
      ["Manufacturer", "MINERALS ROUTE (PRIVATE) LIM", "Ingredients", "Pure Himalayan Salt"],
      ["Content", "Himalayan Pink Salt", "Address", "Pakistan"],
      ["Instruction for use", "Use with washed and dry hands", "Shelf Life", "3 year"],
      ["Place of Origin", "Pakistan", "Product Type", "Salt"],
      ["Processing Type", "Unrefined", "Color", "Pink"],
      ["Additives", "Natural", "Purity (%)", "99.99"],
      ["Weight (kg)", "0.5", "Brand Name", "North Himalayan Salt"],
      ["Model Number", "MRPL-HPS-0017", "Product Name", "Himalayan Pink Salt"],
      ["Keywords", "Natural Himalayan Pink Salt", "Colors", "Pink"],
      ["Origin", "Pakistan", "Usage", "Seasoned Salt"],
      ["Feature", "100% Natural", "Logo", "Customized Logo Print"],
      ["Packing", "As per customer demand", "Quality", "100% High Quality"],
      ["MOQ", "230 Pcs", "", ""],
    ],
    descriptionParagraphs: [
      "Product Description",
      "Himalayan Edible Salt is a pure and natural mineral-rich salt sourced from the Himalayan region of Pakistan. Known for its natural pink color and essential 84 trace minerals, it is widely used for cooking, seasoning, and healthy food preparation.",
      "Natural and Unrefined",
      "This edible pink salt is unrefined and free from artificial additives, making it a clean and natural alternative to processed table salt.",
      "Daily Kitchen Use",
      "Ideal for home kitchens, restaurants, and foodservice applications for seasoning, cooking, and finishing.",
      "Consistent Quality",
      "Processed and packed under strict quality standards to maintain purity, color consistency, and food safety.",
    ],
    referenceImages: [
      "/North%20himaliyan%20salt/pink%20salt/Image_fx%20-%202026-03-19T153835.734.png",
      "/North%20himaliyan%20salt/pink%20salt/Image_fx%20-%202026-03-19T153837.644.png",
    ],
  },
  "salt-lamps": {
    hero: {
      title: "Himalayan Salt",
      subtitle: "Lamps",
      image: "/North%20himaliyan%20salt/lamp/lamp.png",
      description:
        "Handcrafted Himalayan Salt Lamps made from natural pink salt crystals that emit a warm, soothing glow. These decorative lamps are popular for home decor, spas, wellness centers, and relaxation spaces.",
    },
    attributes: [
      ["Material", "Natural Himalayan Salt", "Product Type", "Salt Lamp"],
      ["Style", "Handcrafted", "Shape", "Natural / Custom"],
      ["Place of Origin", "Pakistan", "Brand Name", "North Himalayan Traders"],
      ["Color", "Pink / Orange", "Use", "Home Decor / Wellness"],
      ["Feature", "Warm Ambient Glow", "Power", "Electrical Fitting"],
      ["Application", "Home, Office, Spa", "Packaging", "Secure Export Packing"],
      ["MOQ", "As required", "Delivery Time", "15-25 Days"],
      ["Quality", "Premium", "Certification", "Available on request"],
    ],
    descriptionParagraphs: [
      "Product Description",
      "Himalayan salt lamps are crafted from genuine natural pink salt crystals sourced from Pakistan. They produce a warm and calming glow that enhances interior ambiance and creates a relaxing environment.",
      "Natural Decorative Lighting",
      "Each lamp has a unique crystal texture and color tone, making every piece distinct for homes, offices, wellness centers, and spas.",
      "Premium Handcrafted Finish",
      "Our lamps are carefully shaped and assembled with quality fittings for reliable use and elegant presentation.",
      "Ideal for Global Retail Supply",
      "Suitable for importers, retailers, and distributors looking for premium lifestyle and decor products.",
    ],
    referenceImages: [
      "/North%20himaliyan%20salt/lamp/Image_fx%20(10).png",
      "/North%20himaliyan%20salt/lamp/Image_fx%20(41).png",
      "/North%20himaliyan%20salt/lamp/Image_fx%20(42).png",
    ],
  },
};
